### ISSUE TITLE
Skin section of "Shop"

### ISSUE THREAD

**Issue by Alien-Kinger** [dangarfield/eve-jita-anywhere#4]
Idk what this is but here ya go!
![firefox_rQvQWAeQO5](https://github.com/dangarfield/eve-jita-anywhere/assets/156119379/4704e8d1-3256-4e4f-b394-6eaf54cba0fb)

**Comment by dangarfield** [comment]
Ah, good spot. There is a lot of incorrect referencing in the Eve Online reference data particularly for skins.

For now, I've fixed this by making sure the `?` icon is displayed for skins.

There is another inconsistency between what we can get from the EVE data - Eg, check out this: https://www.jita.space/market

I will close this for now. But I think the 'icons and content' for market icons need to be improved, but it's a nasty piece of work because the data is so 'dirty' compared to the game. I'll close this for now and we can address others as they arise. Thanks

**Comment by dangarfield** [comment]
Slight update: All market groups icons are fixed (which is better than pretty much all other third party sites, I haven't ever seen it 100% correct anywhere else!)

The only exception are SKIN icons. They are almost complete. I'll reopen this ticket so that I complete it properly.

**Comment by dangarfield** [comment]
All skin icons behaviour appears to be fixed now. Better than https://everef.net/market/2104
